vaadin:
  launch-browser: true
spring:
  application:
    name: vaadin-website

  mail:
    host: smtp.gmail.com
    port: 587
    username: antoine.haz@gmail.com
    password: ${GOOGLE_PASSWORD}
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true